classdef AllInclusiveFeatureSet < FeatureCreators.Base
% AllInclusiveFeatureSet Specifies a feature set consisting of:
%   see AllInclusiveFeatureSet.getAFErequests()

    %% --------------------------------------------------------------------
    properties (SetAccess = private)
        deltasLevels;
    end
    
    %% --------------------------------------------------------------------
    methods (Static)
    end
    
    %% --------------------------------------------------------------------
    methods (Access = public)
        
        function obj = AllInclusiveFeatureSet( )
            obj = obj@FeatureCreators.Base();
        end
        %% ----------------------------------------------------------------

        function afeRequests = getAFErequests( obj )
            commonParams = {...
                'rm_wSizeSec', 25E-3,...
                'rm_hSizeSec', 10E-3,... % DO NOT CHANGE -- important for gabor filters
                'rm_decaySec', 8E-3,...
                'pp_bNormalizeRMS', true, ...
                'pp_intTimeSecRMS', 4, ...
                'pp_bBinauralRMS', false ...
                };

            afeRequests{1}.name = 'amsFeatures';
            afeRequests{1}.params = genParStruct( ...
                commonParams{:}, ...
                'fb_nChannels', 16, ...
                'ams_fbType', 'log', ...
                'ams_nFilters', 8, ...
                'ams_lowFreqHz', 2, ...
                'ams_highFreqHz', 256', ...
                'ams_wSizeSec', 128e-3, ...
                'ams_hSizeSec', 32e-3 ...
                );
            afeRequests{2}.name = 'gabor';
            afeRequests{2}.params = genParStruct( ...
                commonParams{:}, ...
                'fb_nChannels', 24 ...
                );
            afeRequests{3}.name = 'spectralFeatures';
            afeRequests{3}.params = genParStruct( ...
                commonParams{:}, ...
                'fb_nChannels', 32 ...
                );

            afeRequests{4}.name = 'ratemap';
            afeRequests{4}.params = genParStruct( ...
                commonParams{:}, ...
                'rm_scaling', 'magnitude', ...
                'fb_nChannels', 24 ...
                );
            afeRequests{5}.name = 'onsetStrength'; % same as Nsrcs set
            afeRequests{5}.params = genParStruct( ...
                commonParams{:}, ...
                'fb_nChannels', 24);
            afeRequests{6}.name = 'crosscorrelation'; % same as dnnLocKs
            afeRequests{6}.params = genParStruct( ...
                'fb_type', 'gammatone', ...
                'fb_lowFreqHz', 80, ...
                'fb_highFreqHz', 8000, ...
                'fb_nChannels', 32, ...
                'ihc_method', 'halfwave', ...
                'ild_wSizeSec', 20E-3, ...
                'ild_hSizeSec', 10E-3, ...
                'rm_wSizeSec', 20E-3, ...
                'rm_hSizeSec', 10E-3, ...
                'rm_scaling', 'power', ...
                'rm_decaySec', 8E-3, ...
                'cc_wSizeSec', 20E-3, ...
                'cc_hSizeSec', 10E-3, ...
                'cc_wname', 'hann');
            afeRequests{7}.name = 'duet'; % same as Nsrcs set
            afeRequests{7}.params = genParStruct( ...
                'duet_wSTFTSec', 0.02,...
                'duet_wDUETSec', (1/2),...
                'duet_hDUETSec', (1/6));
            afeRequests{8}.name = 'itd'; % same as segmentationKs
            afeRequests{8}.params = genParStruct( ...
                'cc_wSizeSec', 0.025,...
                'cc_hSizeSec', 0.01,...
                'ild_wSizeSec', 25E-3, ...
                'ild_hSizeSec', 10E-3, ...
                'cc_maxDelaySec', 0.001,...
                'pp_bMiddleEarFiltering', true,...
                'pp_bNormalizeRMS', true,...
                'ihc_method', 'dau',...
                'fb_type', 'gammatone',...
                'fb_nChannels', 24);
            afeRequests{9}.name = 'ild'; % same as dnnLocKs
            afeRequests{9}.params = genParStruct(...
                'fb_type', 'gammatone', ...
                'fb_lowFreqHz', 80, ...
                'fb_highFreqHz', 8000, ...
                'fb_nChannels', 32, ...
                'ihc_method', 'halfwave', ...
                'ild_wSizeSec', 20E-3, ...
                'ild_hSizeSec', 10E-3, ...
                'rm_wSizeSec', 20E-3, ...
                'rm_hSizeSec', 10E-3, ...
                'rm_scaling', 'power', ...
                'rm_decaySec', 8E-3, ...
                'cc_wSizeSec', 20E-3, ...
                'cc_hSizeSec', 10E-3, ...
                'cc_wname', 'hann');
            afeRequests{10}.name = 'ild'; % same as segmentationKs
            afeRequests{10}.params = genParStruct(...
                'cc_wSizeSec', 0.025,...
                'cc_hSizeSec', 0.01,...
                'ild_wSizeSec', 25E-3, ...
                'ild_hSizeSec', 10E-3, ...
                'cc_maxDelaySec', 0.001,...
                'pp_bMiddleEarFiltering', true,...
                'pp_bNormalizeRMS', true,...
                'ihc_method', 'dau',...
                'fb_type', 'gammatone',...
                'fb_nChannels', 24);
        end
        %% ----------------------------------------------------------------

        function x = constructVector( obj )
            % constructVector for each feature: compress, scale, average
            %   over left and right channels, construct individual feature names
            %   returned flattened feature vector for entire block
            %   The AFE data is indexed according to the order in which the requests
            %   where made
            % 
            %   See getAFErequests
            
            % afeIdx 2: gabor
            assert( false );
            gbR = obj.makeBlockFromAfe( 2, 1, ...
                @(a)(compressAndScale( a.Data, 0.33, @(x)(median( x(x>0.01) )), 0 )), ...
                {@(a)(a.Name), @(a)([num2str(size(a.Data,2)) '-ch']), @(a)(a.Channel)}, ...
                {'t'}, ...
                {@(a)(strcat('ft#', a.fList))} );
            gbL = obj.makeBlockFromAfe( 2, 2, ...
                @(a)(compressAndScale( a.Data, 0.33, @(x)(median( x(x>0.01) )), 0 )), ...
                {@(a)(a.Name), @(a)([num2str(size(a.Data,2)) '-ch']), @(a)(a.Channel)}, ...
                {'t'}, ...
                {@(a)(strcat('ft#', a.fList))} );
            gb = obj.combineBlocks( @(b1,b2)(0.5*b1+0.5*b2), 'LRmean', gbR, gbL );
            % afeIdx 3: spectralFeatures
            spfR = obj.makeBlockFromAfe( 3, 1, ...
                @(a)(compressAndScale( a.Data, 0.33 )), ...
                {@(a)(a.Name),[num2str(obj.freqChannelsStatistics) '-ch'], ...
                @(a)(a.Channel)}, ...
                {'t'}, ...
                {@(a)(a.fList)} );
            spfL = obj.makeBlockFromAfe( 3, 2, ...
                @(a)(compressAndScale( a.Data, 0.33 )), ...
                {@(a)(a.Name),[num2str(obj.freqChannelsStatistics) '-ch'],...
                @(a)(a.Channel)}, ...
                {'t'}, ...
                {@(a)(a.fList)} );
            spf = obj.combineBlocks( @(b1,b2)(0.5*b1+0.5*b2), 'LRmean', spfR, spfL );
            xb = obj.concatBlocks( 2, gb, spf );
            x = obj.block2feat( xb, ...
                @(b)(lMomentAlongDim( b, [1,2,3], 1, true )), ...
                2, @(idxs)(sort([idxs idxs idxs])),...
                {{'1.LMom',@(idxs)(idxs(1:3:end))},...
                 {'2.LMom',@(idxs)(idxs(2:3:end))},...
                 {'3.LMom',@(idxs)(idxs(3:3:end))}} );
            for ii = 1:obj.deltasLevels
                xb = obj.transformBlock( xb, 1, ...
                    @(b)(b(2:end,:) - b(1:end-1,:)), ...
                    @(idxs)(idxs(1:end-1)),...
                    {[num2str(ii) '.delta']} );
                xtmp = obj.block2feat( xb, ...
                    @(b)(lMomentAlongDim( b, [1,2], 1, true )), ...
                    2, @(idxs)(sort([idxs idxs])),...
                    {{'1.LMom',@(idxs)(idxs(1:4:end))},...
                     {'2.LMom',@(idxs)(idxs(2:4:end))}} );
                x = obj.concatFeats( x, xtmp );
            end
            % afeIdx 1: amsFeatures and generate corresponding feature names
            modR = obj.makeBlockFromAfe( 1, 1, ...
                @(a)(compressAndScale( a.Data, 0.33 )), ...
                {@(a)(a.Name), @(a)([num2str(numel(a.cfHz)) '-ch']), @(a)(a.Channel)}, ...
                {'t'}, ...,
                {@(a)(strcat('f', arrayfun(@(f)(num2str(f)), a.cfHz,'UniformOutput', false)))}, ...
                {@(a)(strcat('mf', arrayfun(@(f)(num2str(f)), a.modCfHz,'UniformOutput', false)))} );
            modL = obj.makeBlockFromAfe( 1, 2, ...
                @(a)(compressAndScale( a.Data, 0.33 )), ...
                {@(a)(a.Name), @(a)([num2str(numel(a.cfHz)) '-ch']), @(a)(a.Channel)}, ... % groups
                {'t'}, ... % varargin: time index
                {@(a)(strcat('f', arrayfun(@(f)(num2str(f)), a.cfHz,'UniformOutput', false)))}, ... % varargin: freq. bins
                {@(a)(strcat('mf', arrayfun(@(f)(num2str(f)), a.modCfHz,'UniformOutput', false)))} ); % vararing: modulation frequencies
            % average between right and left channels
            mod = obj.combineBlocks( @(b1,b2)(0.5*b1+0.5*b2), 'LRmean', modR, modL );
            mod = obj.reshapeBlock( mod, 1 ); % flatten
            % append l-moments
            x = obj.concatFeats( x, obj.block2feat( mod, ...
                @(b)(lMomentAlongDim( b, [1,2], 1, true )), ...
                2, @(idxs)(sort([idxs idxs])),...
                {{'1.LMom', @(idxs)(idxs(1:2:end))},...
                 {'2.LMom', @(idxs)(idxs(2:2:end))}} ) );
            % append first derivative
            for ii = 1:obj.deltasLevels
                mod = obj.transformBlock( mod, 1, ...
                    @(b)(b(2:end,:) - b(1:end-1,:)), ...
                    @(idxs)(idxs(1:end-1)),...
                    {[num2str(ii) '.delta']} );
                x = obj.concatFeats( x, obj.block2feat( mod, ...
                    @(b)(lMomentAlongDim( b, [1,2], 1, true )), ...
                    2, @(idxs)(sort([idxs idxs])),...
                    {{'1.LMom', @(idxs)(idxs(1:3:end))},...
                     {'2.LMom', @(idxs)(idxs(2:3:end))}} ) );
            end
        end
        %% ----------------------------------------------------------------
        
        function outputDeps = getFeatureInternOutputDependencies( obj )
            outputDeps.deltasLevels = obj.deltasLevels;
            classInfo = metaclass( obj );
            [classname1, classname2] = strtok( classInfo.Name, '.' );
            if isempty( classname2 ), outputDeps.featureProc = classname1;
            else outputDeps.featureProc = classname2(2:end); end
            outputDeps.v = 1;
        end
        %% ----------------------------------------------------------------
        
    end
    
    %% --------------------------------------------------------------------
    methods (Access = protected)
    end
    
end

