classdef FeatureSetRawRmAms2ChCcIld < FeatureCreators.Base
% 

    %% --------------------------------------------------------------------
    properties (SetAccess = private)
        freqChannels;   % no. of frequency bins for rate maps
        amFreqChannels; % no. of frequency bins for amsFeatures
        amChannels;     % no. of modulation frequencies
        rm_scaling;
        wSizeSec;       % use same values for ratemap, ild and cc
        hSizeSec;       % use same values for ratemap, ild and cc
    end
    
    %% --------------------------------------------------------------------
    methods (Static)
    end
    
    %% --------------------------------------------------------------------
    methods (Access = public)
        
        function obj = FeatureSetRawRmAms2ChCcIld( )
            obj = obj@FeatureCreators.Base();            
            obj.freqChannels = 16;
            obj.amFreqChannels = 8;
            obj.amChannels = 9;
            obj.rm_scaling = 'magnitude';
            obj.wSizeSec = 20E-3; % default value for rm, cc and ild wSizeSec is 20E-3
            obj.hSizeSec = 10E-3; % default value for rm, cc and ild hSizeSec is 10E-3
        end
        %% ----------------------------------------------------------------

        function afeRequests = getAFErequests( obj )
            afeRequests{1}.name = 'amsFeatures';
            afeRequests{1}.params = genParStruct( ...
                'pp_bNormalizeRMS', false, ...
                'fb_nChannels', obj.amFreqChannels, ...
                'ams_fbType', 'log', ...
                'ams_nFilters', obj.amChannels, ...
                'ams_lowFreqHz', 1, ...
                'ams_highFreqHz', 256' ...
                );
            afeRequests{2}.name = 'ratemap';
            afeRequests{2}.params = genParStruct( ...
                'pp_bNormalizeRMS', false, ...
                'rm_scaling', 'magnitude', ...
                'fb_nChannels', obj.freqChannels ...
                );
            param = genParStruct(...
                'fb_type', 'gammatone', ...
                'fb_lowFreqHz', 80, ...
                'fb_highFreqHz', 8000, ...
                'fb_nChannels', obj.freqChannels, ...
                'ihc_method', 'halfwave', ...
                'ild_wSizeSec', obj.wSizeSec, ...
                'ild_hSizeSec', obj.hSizeSec, ...
                'rm_wSizeSec', obj.wSizeSec, ...
                'rm_hSizeSec', obj.hSizeSec, ...
                'rm_scaling', obj.rm_scaling, ...
                'cc_wSizeSec', obj.wSizeSec, ...
                'cc_hSizeSec', obj.hSizeSec ...
                );
            afeRequests{3}.name = 'crosscorrelation';
            afeRequests{3}.params = param;
            afeRequests{4}.name = 'ild';
            afeRequests{4}.params = param;
        end
        %% ----------------------------------------------------------------

        function x = constructVector( obj )
            % afeIdx 2: ratemap
            % first the left, then the right channel
            rmL = obj.makeBlockFromAfe( 2, 1, ...
                @(a)(compressAndScale( a.Data, 0.33, @(x)(median( x(x>0.01) )), 0 )), ...
                {@(a)(a.Name),@(a)([num2str(numel(a.cfHz)) '-ch']),@(a)(a.Channel)}, ...
                {@(a)(strcat('t', arrayfun(@(t)(num2str(t)),1:size(a.Data,1),'UniformOutput',false)))}, ...
                {@(a)(strcat('f', arrayfun(@(f)(num2str(f)),a.cfHz,'UniformOutput',false)))} );
            x = obj.reshape2featVec( rmL );
            rmR = obj.makeBlockFromAfe( 2, 2, ...
                @(a)(compressAndScale( a.Data, 0.33, @(x)(median( x(x>0.01) )), 0 )), ...
                {@(a)(a.Name),@(a)([num2str(numel(a.cfHz)) '-ch']),@(a)(a.Channel)},...
                {@(a)(strcat('t', arrayfun(@(t)(num2str(t)),1:size(a.Data,1),'UniformOutput',false)))},...
                {@(a)(strcat('f', arrayfun(@(f)(num2str(f)),a.cfHz,'UniformOutput',false)))} );
            x = obj.concatFeats( x, obj.reshape2featVec( rmR ) );
            % afeIdx 1: amsFeatures and generate corresponding feature names
            % first the left, then the right channel
            modL = obj.makeBlockFromAfe( 1, 1, ...
                @(a)(compressAndScale( a.Data, 0.33 )), ...
                {@(a)(a.Name),@(a)([num2str(numel(a.cfHz)) '-ch']),@(a)(a.Channel)}, ...
                {@(a)(strcat('t', arrayfun(@(t)(num2str(t)),1:size(a.Data,1),'UniformOutput',false)))}, ...
                {@(a)(strcat('f', arrayfun(@(f)(num2str(f)),a.cfHz,'UniformOutput',false)))},...
                {@(a)(strcat('mf', arrayfun(@(f)(num2str(f)),a.modCfHz,'UniformOutput',false)))} );
            mod = obj.reshapeBlock( modL, 1 );
            x = obj.concatFeats( x, obj.reshape2featVec( mod ) );
            modR = obj.makeBlockFromAfe( 1, 2, ...
                @(a)(compressAndScale( a.Data, 0.33 )), ...
                {@(a)(a.Name),@(a)([num2str(numel(a.cfHz)) '-ch']),@(a)(a.Channel)}, ...
                {@(a)(strcat('t', arrayfun(@(t)(num2str(t)),1:size(a.Data,1),'UniformOutput',false)))}, ...
                {@(a)(strcat('f', arrayfun(@(f)(num2str(f)),a.cfHz,'UniformOutput',false)))},...
                {@(a)(strcat('mf', arrayfun(@(f)(num2str(f)),a.modCfHz,'UniformOutput',false)))} );
            mod = obj.reshapeBlock( modR, 1 );
            x = obj.concatFeats( x, obj.reshape2featVec( mod ) );
            % afeIdx 3: corss correltation
            ccf = obj.makeBlockFromAfe( 3, 1, ...
                @(a)(compressAndScale( a.Data, 0.33 )), ...
                {@(a)(a.Name),@(a)([num2str(numel(a.cfHz)) '-ch']),@(a)(a.Channel)}, ...
                {@(a)(strcat('t', arrayfun(@(t)(num2str(t)),1:size(a.Data,1),'UniformOutput',false)))}, ...
                {@(a)(strcat('f', arrayfun(@(f)(num2str(f)),a.cfHz,'UniformOutput',false)))}, ...
                {@(a)(strcat('l', arrayfun(@(l)(num2str(l)),a.lags','UniformOutput',false)))} ...
                );
            ccf = obj.reshapeBlock( ccf, 1 );
            x = obj.concatFeats( x, obj.reshape2featVec( ccf ) );
            % afeIdx 4: ild
            ild = obj.makeBlockFromAfe( 4, 1, ...
                @(a)(compressAndScale( a.Data, 0.33 )), ...
                {@(a)(a.Name),@(a)([num2str(numel(a.cfHz)) '-ch']),@(a)(a.Channel)}, ...
                {@(a)(strcat('t', arrayfun(@(t)(num2str(t)),1:size(a.Data,1),'UniformOutput',false)))}, ...
                {@(a)(strcat('f', arrayfun(@(f)(num2str(f)),a.cfHz,'UniformOutput',false)))} );
            x = obj.concatFeats( x, obj.reshape2featVec( ild ) );
        end
        %% ----------------------------------------------------------------
        
        function outputDeps = getFeatureInternOutputDependencies( obj )
            outputDeps.Channels = obj.freqChannels;  
            outputDeps.amChannels = obj.amChannels;   
            outputDeps.amFreqChannels = obj.amFreqChannels;  
            outputDeps.wSizeSec = obj.wSizeSec;
            outputDeps.hSizeSec = obj.hSizeSec;
            outputDeps.rm_scaling = obj.rm_scaling; 
            classInfo = metaclass( obj );
            [classname1, classname2] = strtok( classInfo.Name, '.' );
            if isempty( classname2 ), outputDeps.featureProc = classname1;
            else outputDeps.featureProc = classname2(2:end); end
            outputDeps.v = 3;
        end
        %% ----------------------------------------------------------------
        
    end
    
    %% --------------------------------------------------------------------
    methods (Access = protected)
    end
    
end

