classdef LocationHypothesis < Hypothesis
    % class LocationHypothsis represents a list of locations where could
    % exist a source, and is generated by LocationKS
    
    properties (SetAccess = private)
        posteriors;                        % Posterior distribution for all angles
        locations;                         % Relative locations
        headOrientation;                   % Head orientation angle
        seenByConfusionKS = false;
        seenByConfusionSolvingKS = false;
    end
    
    methods
        function obj = LocationHypothesis(headOrientation, locations, posteriors)
            obj.headOrientation = headOrientation;
            obj.locations = locations;
            obj.posteriors = posteriors;
        end
        function obj = setSeenByConfusionKS(obj)
            obj.seenByConfusionKS = true;
        end
        function obj = setSeenByConfusionSolvingKS(obj)
            obj.seenByConfusionSolvingKS = true;
        end
    end
    
end
