function [bestCV, bestCVstd, smallestWithinBest] = snrCmpCvAndTestPerf( ...
    dirName, className, snrtr, snrte, bplot )

if nargin < 5, bplot = 0; end;

[bestCV, bestCVstd, smallestWithinBest] = ...
    dirCmpCvAndTestPerf( dirName, className, snrtr, snrte, ...
                         @(m)(m.lastDataProcParams.extern.extern.sceneConfig1.sceneConfig.SNRs.val), ...
                         @(m)(m.lastDataProcParams.extern.extern.sceneConfig1.sceneConfig.SNRs.val), ...
                         bplot );
                     