function [bestCV, bestCVstd, smallestWithinBest] = azmCmpCvAndTestPerf( dirName, className, azmtr, azmte, bplot )

if nargin < 5, bplot = 0; end;

[bestCV, bestCVstd, smallestWithinBest] = ...
    dirCmpCvAndTestPerf( dirName, className, azmtr, azmte, ...
                         @(m)(m.azm), ...
                         @(m)(m.lastDataProcParams.extern.extern.sceneConfig1.sceneConfig.angleSignal.val),...
                         bplot );
                     